#! /bin/sh

killall -q polybar

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends -b &
polybar &
~/.fehbg

bspc monitor -d     

bspc config border_width        0
bspc config window_gap          48
bspc config border_radius       16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
