#! /bin/sh

killall -q polybar

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends -b &
polybar &
feh --bg-fill ~/Wallpapers/purp.jpg &
xsetroot -cursor_name left_ptr

bspc monitor -d     

bspc config border_width        0
bspc config window_gap          48
bspc config border_radius       16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
